version: '3.5'

volumes:
  solrdata:         # Store solr cores' data and configs

services:
  orthosearch:
    image: veupathdb/site-search:${SITESEARCH_TAG:-latest}
    environment:
      SOLR_URL: http://solr:${SOLR_PORT:-8983}/solr/orthosearch
    networks:
      - internal
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.orthosearch-${ROUTER:-os-dev}.rule=Host(`${ORTHO_DOMAIN:-orthosearch-dev.local.apidb.org}`)"
      - "traefik.http.routers.orthosearch-${ROUTER:-os-dev}.tls=true"
      - "traefik.http.routers.orthosearch-${ROUTER:-os-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${SITESEARCH_WATCHTOWER:-false}"

  edasearch:
    image: veupathdb/site-search:${SITESEARCH_TAG:-latest}
    environment:
      SOLR_URL: http://solr:${SOLR_PORT:-8983}/solr/edasearch
    networks:
      - internal
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.edasearch-${ROUTER:-es-dev}.rule=Host(`${EDA_DOMAIN:-edasearch-dev.local.apidb.org}`)"
      - "traefik.http.routers.edasearch-${ROUTER:-es-dev}.tls=true"
      - "traefik.http.routers.edasearch-${ROUTER:-es-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${SITESEARCH_WATCHTOWER:-false}"

  sitesearch:
    image: veupathdb/site-search:${SITESEARCH_TAG:-latest}
    environment:
      SOLR_URL: http://solr:${SOLR_PORT:-8983}/solr/site_search
    networks:
      - internal
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.sitesearch-${ROUTER:-ss-dev}.rule=Host(`${DOMAIN:-sitesearch-dev.local.apidb.org}`)"
      - "traefik.http.routers.sitesearch-${ROUTER:-ss-dev}.tls=true"
      - "traefik.http.routers.sitesearch-${ROUTER:-ss-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${SITESEARCH_WATCHTOWER:-false}"
  solr:
    image: veupathdb/solr:${SOLR_TAG:-latest}
    command: ["solr-precreate", "site_search", "/opt/solr/server/solr/configsets/site-search"]
    environment:
      SOLR_JAVA_MEM: ${SOLR_JAVA_MEM:--Xms128m -Xmx128m}
      REPO_ENV: ${SOLR_REPO_ENV:-dev}
      REPO_KEY: ${SOLR_REPO_KEY}
      REPO_HOST: ${SOLR_REPO_HOST}
      REPO_REMOTE_PATH: ${SOLR_REPO_REMOTE_PATH}
      REPO_REMOTE_PORT: ${SOLR_REPO_REMOTE_PORT}
      # mitigation for cve-2021-44228
      SOLR_OPTS: "$SOLR_OPTS -Dlog4j2.formatMsgNoLookups=true"
    volumes:
      - solrdata:/var/solr
    networks:
      - internal
      - traefik
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.solr-${ROUTER:-ss-dev}.rule=Host(`solr-${DOMAIN:-sitesearch-dev.local.apidb.org}`)"
      - "traefik.http.routers.solr-${ROUTER:-ss-dev}.tls=true"
      - "traefik.http.routers.solr-${ROUTER:-ss-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${SOLR_WATCHTOWER:-false}"

networks:
  internal: # internal network
    external: false
  traefik: # external network
    external: true
