C_BLUE := "\\033[94m"
C_NONE := "\\033[0m"
C_CYAN := "\\033[36m"

.PHONY: default
default:
	@echo ""
	@echo "Please choose one of:"
	@echo ""
	@echo "$(C_BLUE)  make jar$(C_NONE)"
	@echo "    Compiles a runnable 'fat jar' from this project and its dependencies"
	@echo ""
	@echo "$(C_BLUE)  make docker$(C_NONE)"
	@echo "    Builds a runnable docker image for this service"
	@echo ""
	@echo "$(C_BLUE)  make clean$(C_NONE)"
	@echo "    Removes files generated by other targets"
	@echo ""

.PHONY: jar
jar: fgputil
	mvn clean package

.PHONY: fgputil
fgputil:
	bash bin/build-fgputil.sh

.PHONY: docker
docker:
	docker build -t site-search .

.PHONY: clean
clean:
	@rm -rf .build target
